begin;

create extension if not exists pgcrypto;

create table if not exists public.wedding_gifts (
  id bigint generated by default as identity primary key,
  name text not null,
  quantity_requested integer not null default 1 check (quantity_requested > 0),
  quantity_reserved integer not null default 0 check (quantity_reserved >= 0),
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.wedding_gifts
drop constraint if exists wedding_gifts_name_key;

create table if not exists public.wedding_rsvps (
  id uuid primary key default gen_random_uuid(),
  guest_name text not null,
  guest_email text not null,
  attendance text not null check (attendance in ('Joyfully attending', 'Regretfully declining')),
  guest_count integer not null check (guest_count >= 1 and guest_count <= 6),
  message text,
  gift_id bigint references public.wedding_gifts(id) on delete set null,
  other_gift text,
  confirmation_email_status text not null default 'pending' check (confirmation_email_status in ('pending', 'sent', 'failed')),
  confirmation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.wedding_rsvp_gifts (
  id bigint generated by default as identity primary key,
  rsvp_id uuid not null references public.wedding_rsvps(id) on delete cascade,
  gift_id bigint not null references public.wedding_gifts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (rsvp_id, gift_id)
);

alter table public.wedding_rsvps
add column if not exists guest_email text;

alter table public.wedding_rsvps
add column if not exists confirmation_email_status text not null default 'pending';

alter table public.wedding_rsvps
add column if not exists confirmation_email_sent_at timestamptz;

alter table public.wedding_gifts enable row level security;
alter table public.wedding_rsvps enable row level security;

drop policy if exists "Anon can read wedding gifts" on public.wedding_gifts;
create policy "Anon can read wedding gifts"
on public.wedding_gifts
for select
to anon
using (is_active = true);

drop function if exists public.submit_wedding_rsvp(text, text, text, integer, text, bigint[], text);
create or replace function public.submit_wedding_rsvp(
  p_guest_name text,
  p_guest_email text,
  p_attendance text,
  p_guest_count integer,
  p_message text default null,
  p_gift_ids bigint[] default null,
  p_other_gift text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rsvp_id uuid;
  v_reserved_names text[];
  v_gift_id bigint;
  v_reserved_name text;
begin
  if p_guest_name is null or btrim(p_guest_name) = '' then
    raise exception 'Guest name is required.';
  end if;

  if p_guest_email is null or btrim(p_guest_email) = '' then
    raise exception 'Email address is required.';
  end if;

  if p_attendance not in ('Joyfully attending', 'Regretfully declining') then
    raise exception 'Attendance selection is invalid.';
  end if;

  if p_guest_count < 1 or p_guest_count > 6 then
    raise exception 'Guest count must be between 1 and 6.';
  end if;

  if p_attendance = 'Joyfully attending' then
    if (p_gift_ids is null or array_length(p_gift_ids, 1) is null) and (p_other_gift is null or btrim(p_other_gift) = '') then
      raise exception 'Please select at least one gift or provide another gift.';
    end if;

    if array_length(coalesce(p_gift_ids, array[]::bigint[]), 1) > 3 then
      raise exception 'You may reserve a maximum of 3 gifts.';
    end if;
  else
    p_gift_ids := null;
    p_other_gift := null;
  end if;

  insert into public.wedding_rsvps (
    guest_name,
    guest_email,
    attendance,
    guest_count,
    message,
    other_gift,
    confirmation_email_status
  ) values (
    btrim(p_guest_name),
    lower(btrim(p_guest_email)),
    p_attendance,
    p_guest_count,
    nullif(btrim(coalesce(p_message, '')), ''),
    nullif(btrim(coalesce(p_other_gift, '')), ''),
    'pending'
  )
  returning id into v_rsvp_id;

  if p_gift_ids is not null then
    foreach v_gift_id in array p_gift_ids loop
      update public.wedding_gifts
      set quantity_reserved = quantity_reserved + 1
      where id = v_gift_id
        and is_active = true
        and quantity_reserved < quantity_requested
      returning name into v_reserved_name;

      if v_reserved_name is null then
        raise exception 'One of the selected gifts is no longer available. Please review your choices and try again.';
      end if;

      insert into public.wedding_rsvp_gifts (rsvp_id, gift_id)
      values (v_rsvp_id, v_gift_id);

      v_reserved_names := array_append(v_reserved_names, v_reserved_name);
    end loop;
  end if;

  return jsonb_build_object(
    'id', v_rsvp_id,
    'guest_name', btrim(p_guest_name),
    'guest_email', lower(btrim(p_guest_email)),
    'gift_names', coalesce(v_reserved_names, array[]::text[]),
    'other_gift', nullif(btrim(coalesce(p_other_gift, '')), ''),
    'message', case
      when p_attendance = 'Joyfully attending' and coalesce(array_length(v_reserved_names, 1), 0) > 0 then
        'Your RSVP has been recorded and your selected gifts have been reserved for you.'
      when p_attendance = 'Joyfully attending' then
        'Your RSVP has been recorded and your gift note has been saved.'
      else
        'Your RSVP has been recorded.'
      end
  );
end;
$$;

grant execute on function public.submit_wedding_rsvp(text, text, text, integer, text, bigint[], text) to anon, authenticated, service_role;

truncate table public.wedding_rsvps, public.wedding_gifts restart identity;

with seed(base_name, item_count, display_order) as (
  values
    ('Bedding set (king size)', 3, 1),
    ('Toaster', 1, 2),
    ('Sandwich maker', 1, 3),
    ('Blender', 1, 4),
    ('Microwave', 1, 5),
    ('Hand mixer', 1, 6),
    ('Ironing board', 1, 7),
    ('Drying rack', 1, 8),
    ('Cutlery set', 1, 9),
    ('Dinner set (white)', 1, 10),
    ('Dinner set (black)', 1, 11),
    ('Dinner set (grey)', 1, 12),
    ('Aprons', 1, 13),
    ('Casserole dish (white)', 1, 14),
    ('Colander (big size)', 1, 15),
    ('Knives set', 1, 16),
    ('Cast iron pots', 1, 17),
    ('Spices rack organizer', 1, 18),
    ('Coffee mugs set', 1, 19),
    ('Placemats', 5, 20),
    ('Serving bowls', 1, 21),
    ('Large bath towels', 3, 22),
    ('Camp chairs', 2, 23),
    ('Floor lamps', 1, 24),
    ('Throw blankets', 2, 25),
    ('Wall art', 3, 26),
    ('Gift card', 2, 27),
    ('Mall voucher', 2, 28),
    ('Tool kit', 1, 29),
    ('Glass set', 2, 30),
    ('Sandwich press', 1, 31),
    ('Chafing dish', 3, 32),
    ('Mattress protector (king)', 1, 33),
    ('Pillow protector (standard pillows)', 2, 34),
    ('Fitted sheet (king size, 200 thread count, 100% cotton)', 2, 35),
    ('Pillow (standard, ballfibre)', 2, 36),
    ('Spa voucher (for two)', 1, 37),
    ('Decorative cushions', 1, 38),
    ('White flower vase', 1, 39),
    ('Room diffusers', 1, 40),
    ('Scented candles', 1, 41),
    ('Vegetable chopper set', 1, 42),
    ('Sound bar', 1, 43),
    ('Salad bowl', 4, 44),
    ('Food storage containers', 6, 45),
    ('Juice jars', 1, 46),
    ('Vegetable rack (metal)', 1, 47),
    ('Potato masher', 1, 48),
    ('Cake stand', 1, 49),
    ('Peeler and kitchen scissors', 1, 50),
    ('Juice maker', 1, 51),
    ('Continental pillows', 2, 52),
    ('Canister set (tea, coffee, sugar)', 1, 53),
    ('Floorwiz spin mop', 1, 54),
    ('Iron', 1, 55)
),
expanded as (
  select
    case
      when item_count > 1 then base_name || ' x1 (' || gift_number || ' of ' || item_count || ')'
      else base_name
    end as name,
    row_number() over (order by display_order, gift_number) as final_order
  from seed
  cross join lateral generate_series(1, item_count) as gift_number
)
insert into public.wedding_gifts (name, quantity_requested, quantity_reserved, display_order, is_active)
select name, 1, 0, final_order, true
from expanded;

commit;
